"use client";
import React, { useState } from 'react';
import { Search, AlertTriangle, TrendingDown, Activity, ShieldAlert, Terminal } from 'lucide-react';
import { LineChart, Line, XAxis, YAxis, Tooltip, ResponsiveContainer } from 'recharts';

export default function Dashboard() {
  const [ticker, setTicker] = useState('');
  const [loading, setLoading] = useState(false);
  const [data, setData] = useState(null);
  const [error, setError] = useState('');

  const analyzeStock = async () => {
    if (!ticker) return;
    setLoading(true);
    setError('');
    setData(null);

    try {
      // Connect to your Python Backend running on port 8000
      const response = await fetch(`http://127.0.0.1:8000/api/analyze/${ticker}`);
      if (!response.ok) throw new Error("Failed to fetch data");
      
      const result = await response.json();
      setData(result);
    } catch (err) {
      setError("Backend is offline or ticker invalid. Make sure 'uvicorn' is running!");
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="min-h-screen bg-slate-50 text-slate-900 p-8 font-sans">
      {/* Header */}
      <header className="max-w-4xl mx-auto mb-12 flex items-center justify-between">
        <div className="flex items-center gap-3">
          <div className="bg-blue-600 p-2 rounded-lg">
            <Activity className="text-white w-6 h-6" />
          </div>
          <div>
            <h1 className="text-2xl font-bold text-slate-900 tracking-tight">HedgeAI</h1>
            <p className="text-slate-500 text-sm">Contrarian Risk Analysis</p>
          </div>
        </div>
      </header>

      {/* Search Box */}
      <main className="max-w-2xl mx-auto">
        <div className="bg-white p-2 rounded-2xl shadow-sm border border-slate-200 flex gap-2 mb-8 transition-all focus-within:ring-2 ring-blue-100 ring-offset-2">
          <input 
            type="text" 
            placeholder="Enter Ticker (e.g., NVDA, TSLA)" 
            className="flex-1 px-4 py-3 outline-none text-lg uppercase placeholder:normal-case"
            value={ticker}
            onChange={(e) => setTicker(e.target.value)}
            onKeyDown={(e) => e.key === 'Enter' && analyzeStock()}
          />
          <button 
            onClick={analyzeStock}
            disabled={loading}
            className="bg-blue-600 hover:bg-blue-700 text-white px-8 py-3 rounded-xl font-medium transition-colors disabled:opacity-50 flex items-center gap-2"
          >
            {loading ? (
              <span className="animate-pulse">Analyzing...</span>
            ) : (
              <>
                <Search className="w-4 h-4" /> Run Analysis
              </>
            )}
          </button>
        </div>

        {/* Error State */}
        {error && (
          <div className="bg-red-50 text-red-600 p-4 rounded-xl border border-red-100 flex items-center gap-3 mb-8 animate-in fade-in slide-in-from-top-2">
            <AlertTriangle className="w-5 h-5" />
            {error}
          </div>
        )}

        {/* Results Dashboard */}
        {data && (
          <div className="space-y-6 animate-in fade-in slide-in-from-bottom-4 duration-500">
            
            {/* Top Card: Ticker & Status */}
            <div className="bg-white p-6 rounded-2xl shadow-sm border border-slate-200 flex justify-between items-center">
              <div>
                <h2 className="text-3xl font-bold">{data.ticker}</h2>
                <span className="text-slate-400 text-sm">Real-Time Analysis</span>
              </div>
              <div className="flex items-center gap-2 bg-slate-100 px-4 py-2 rounded-full border border-slate-200">
                <Terminal className="w-4 h-4 text-slate-500" />
                <span className="text-sm font-mono text-slate-600">Claude 3.5 Sonnet</span>
              </div>
            </div>

            {/* The AI Report */}
            <div className="bg-white rounded-2xl shadow-lg border border-slate-200 overflow-hidden">
              <div className="bg-slate-900 p-4 flex items-center gap-2 border-b border-slate-800">
                <ShieldAlert className="text-blue-400 w-5 h-5" />
                <h3 className="text-white font-medium">Risk Memo</h3>
              </div>
              
              <div className="p-8 prose prose-slate max-w-none">
                {/* We render the markdown-style text from Claude safely */}
                <div className="whitespace-pre-wrap text-slate-700 leading-relaxed text-lg">
                  {data.analysis}
                </div>
              </div>
              
              <div className="bg-slate-50 p-4 border-t border-slate-200 text-center text-xs text-slate-400">
                Generated by AI • Not Financial Advice • For Research Only
              </div>
            </div>

          </div>
        )}
      </main>
    </div>
  );
}
